# Generated by Django 4.1.6 on 2023-05-06 12:56

import account.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last name')),
                ('password', models.CharField(max_length=100)),
                ('account_created', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100, unique=True)),
                ('business_title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Manager', 'manager'), ('Developer', 'developer'), ('Owner', 'owner'), ('Consultant', 'consultant'), ('Contractor', 'contractor'), ('Vp/Director', 'vp/director')], default='Manager', max_length=100)),
                ('open_now', models.BooleanField(default=True)),
                ('business_phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None)),
                ('business_email', models.EmailField(default=None, max_length=254, null=True)),
                ('business_website', models.CharField(default=None, max_length=200, null=True)),
                ('business_address', models.CharField(default=None, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('issued_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='10:00')),
                ('end_time', models.TimeField(default='16:00')),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default=account.models.default_days_of_week, size=None)),
                ('business_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation_schedule', to='account.business_profile')),
            ],
        ),
    ]
