# Generated by Django 4.1.6 on 2023-02-16 08:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_verified_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(default=None)),
                ('dateofbirth', models.DateField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('notes', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
                ('fieldlist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('policy_status', models.BooleanField(default=False)),
                ('policy', models.TextField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bussiness_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=100, unique=True)),
                ('public_link', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Manager', 'manager'), ('Developer', 'developer'), ('Owner', 'owner'), ('Consultant', 'consultant'), ('Contractor', 'contractor'), ('Vp/Director', 'vp/director')], default='Manager', max_length=100)),
                ('open_now', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
