# Generated by Django 4.1.6 on 2023-03-04 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_fields_fieldlist_bussiness_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(default=None)),
                ('dateofbirth', models.DateField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('party_size', models.IntegerField(default=None)),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('notes', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
