# Generated by Django 4.1.6 on 2023-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_waitlist_delete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='dateofbirth',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='first_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='notes',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='party_size',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='phone_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
