# Generated by Django 4.1.6 on 2023-03-04 16:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_waitlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None),
        ),
    ]
