# Generated by Django 4.1.6 on 2023-03-04 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_waitlist_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
