# Generated by Django 4.1.6 on 2023-03-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_waitlist_added_time_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlist',
            options={'get_latest_by': 'added_time'},
        ),
    ]
