# Generated by Django 4.1.6 on 2023-03-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_waitlist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='FieldList',
        ),
        migrations.DeleteModel(
            name='Waitlist',
        ),
    ]
