# Generated by Django 4.1.6 on 2023-03-09 11:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_waitlist_user_delete_fieldlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness_profile',
            name='bussiness_address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bussiness_profile',
            name='bussiness_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bussiness_profile',
            name='bussiness_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='bussiness_profile',
            name='bussiness_website',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
