# Generated by Django 4.1.6 on 2023-03-09 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_bussiness_profile_bussiness_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=100, unique=True)),
                ('public_link', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Manager', 'manager'), ('Developer', 'developer'), ('Owner', 'owner'), ('Consultant', 'consultant'), ('Contractor', 'contractor'), ('Vp/Director', 'vp/director')], default='Manager', max_length=100)),
                ('open_now', models.BooleanField(default=True)),
                ('business_phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None)),
                ('business_email', models.EmailField(default=None, max_length=254, null=True)),
                ('business_website', models.CharField(default=None, max_length=200, null=True)),
                ('business_address', models.CharField(default=None, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bussiness_Profile',
        ),
    ]
