# Generated by Django 4.1.6 on 2023-03-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_business_profile_delete_bussiness_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_profile',
            old_name='bussiness_name',
            new_name='business_name',
        ),
    ]
