# Generated by Django 4.1.6 on 2023-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_bussiness_name_business_profile_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile',
            name='bussiness_detail_name',
            field=models.CharField(default='Mysaloon', max_length=100),
        ),
    ]
