# Generated by Django 4.1.6 on 2023-03-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_business_profile_bussiness_detail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_profile',
            name='bussiness_detail_name',
        ),
        migrations.AddField(
            model_name='business_profile',
            name='business_title',
            field=models.CharField(default='merosal', max_length=100),
        ),
    ]
