# Generated by Django 4.1.6 on 2023-03-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_business_profile_bussiness_detail_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_profile',
            name='business_title',
            field=models.CharField(max_length=100),
        ),
    ]
