# Generated by Django 4.1.6 on 2023-05-02 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_business_profile_business_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
