# Generated by Django 4.1.6 on 2023-05-02 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_business_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
