# Generated by Django 4.1.6 on 2023-05-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_business_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_profile',
            name='public_id',
        ),
    ]
