# Generated by Django 4.1.6 on 2023-05-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_business_profile_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_profile',
            name='public_link',
        ),
    ]
