# Generated by Django 4.1.6 on 2023-05-06 12:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='resource_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='service_images/')),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=5)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('buffer_time', models.IntegerField(default=1)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None)),
                ('dateofbirth', models.DateField(default=None, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('party_size', models.IntegerField(default=None, null=True)),
                ('first_name', models.CharField(default=None, max_length=100, null=True)),
                ('last_name', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('served_time', models.DateTimeField(default=None, null=True)),
                ('serving_started_time', models.DateTimeField(default=None, null=True)),
                ('serving', models.BooleanField(default=False)),
                ('served', models.BooleanField(default=False)),
                ('self_checkin', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_for', to='waitlistapp.resources')),
                ('service', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_taken', to='waitlistapp.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'added_time',
            },
        ),
        migrations.AddField(
            model_name='resources',
            name='services',
            field=models.ManyToManyField(to='waitlistapp.services'),
        ),
        migrations.AddField(
            model_name='resources',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=100)),
                ('edited_time', models.DateTimeField(auto_now=True)),
                ('customer_on_waitlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='waitlistapp.waitlist')),
            ],
        ),
        migrations.CreateModel(
            name='FieldList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
                ('fieldlist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('policy_status', models.BooleanField(default=False)),
                ('policy', models.TextField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
