# Generated by Django 4.1.6 on 2023-03-08 03:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None)),
                ('dateofbirth', models.DateField(default=None, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('party_size', models.IntegerField(default=None, null=True)),
                ('first_name', models.CharField(default=None, max_length=100, null=True)),
                ('last_name', models.CharField(default=None, max_length=100, null=True)),
                ('notes', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'added_time',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('edited_time', models.DateTimeField(auto_now=True)),
                ('customer_on_waitlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='waitlistapp.waitlist')),
            ],
        ),
        migrations.CreateModel(
            name='FieldList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
                ('fieldlist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('policy_status', models.BooleanField(default=False)),
                ('policy', models.TextField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
