# Generated by Django 4.1.6 on 2023-03-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.CharField(max_length=100),
        ),
    ]
