# Generated by Django 4.1.6 on 2023-05-13 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ValidationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waitlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='waitlistapp.waitlist')),
            ],
        ),
    ]
