# Generated by Django 4.1.6 on 2023-03-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0003_remove_waitlist_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='notes',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
