# Generated by Django 4.1.6 on 2023-03-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0004_waitlist_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='notes',
        ),
    ]
