# Generated by Django 4.1.6 on 2023-05-16 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waitlistapp', '0004_alter_waitlist_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_on_queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_of', to=settings.AUTH_USER_MODEL)),
                ('waitlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_for', to='waitlistapp.waitlist')),
            ],
        ),
    ]
