# Generated by Django 4.1.6 on 2023-03-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0005_remove_waitlist_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='service_images/')),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=5)),
                ('price', models.IntegerField(blank=True)),
                ('buffer_time', models.IntegerField(default=1)),
                ('max_booking_per_day', models.IntegerField(blank=True, default=None)),
            ],
        ),
    ]
