# Generated by Django 4.1.6 on 2023-05-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0006_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='currently_serving',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_served_waitlist', to='waitlistapp.waitlist'),
        ),
    ]
