# Generated by Django 4.1.6 on 2023-03-10 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waitlistapp', '0006_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
