# Generated by Django 4.1.6 on 2023-03-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0007_services_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='max_booking_per_day',
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
