# Generated by Django 4.1.6 on 2023-04-28 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waitlistapp', '0008_remove_services_max_booking_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='serving',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='resource_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
