# Generated by Django 4.1.6 on 2023-05-01 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waitlistapp', '0009_waitlist_served_waitlist_serving_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='servicelist', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
