# Generated by Django 4.1.6 on 2023-05-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0010_service_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_resource',
            name='resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='servicelist', to='waitlistapp.resources'),
        ),
        migrations.AlterField(
            model_name='service_resource',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='waitlistapp.services'),
        ),
    ]
