# Generated by Django 4.1.6 on 2023-05-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0012_resources_services_delete_service_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='served_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='serving_started_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
