# Generated by Django 4.1.6 on 2023-05-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0013_waitlist_served_time_waitlist_serving_started_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='resource',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_for', to='waitlistapp.resources'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_taken', to='waitlistapp.services'),
        ),
    ]
