# Generated by Django 4.1.6 on 2023-05-02 15:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0022_remove_business_profile_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_access', models.BooleanField(default=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_link_to', to='account.business_profile')),
            ],
        ),
    ]
