# Generated by Django 4.1.6 on 2023-05-04 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joinlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_link_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
