# Generated by Django 4.1.6 on 2023-05-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'hWSodOEGci8FmOmLa2Kkax_TiI6nz2lCW062unQsI4E='),
        ),
    ]
