# Generated by Django 4.1.6 on 2023-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0002_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'CUw9Lbq2g9mBqQ-EPBUZhIQO4X89_HFeIcV4WmaDUs0='),
        ),
    ]
