# Generated by Django 4.1.6 on 2023-05-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0002_alter_public_link_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'k1lE7RK3_Hb9IAsSJ0VICkAuh0pih-FFNr-OBNOiU8Q='),
        ),
    ]
