# Generated by Django 4.1.6 on 2023-05-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0002_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'Z0gjy2uGpLNAK8xhWCh4Ga3GXNMpxhQi2Ruq8qZXdgY='),
        ),
    ]
