# Generated by Django 4.1.6 on 2023-05-05 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_business_profile_public_link'),
        ('joinlink', '0003_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'oGbj2knaJ0dVb30beosXkyQi1JGa25DgG7T0lBbc-cY='),
        ),
        migrations.AlterField(
            model_name='public_link',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_link_to', to='account.business_profile'),
        ),
    ]
