# Generated by Django 4.1.6 on 2023-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0004_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'02Q1jw3Dy-qWh7DctrkYNVrVtwIr1I7A-t9H7J11I6o='),
        ),
    ]
