# Generated by Django 4.1.6 on 2023-05-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0004_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'XJvPxhEB4N7hAgTw5-J-qz-FwH5QC7MJp8Szdn5c8gI='),
        ),
    ]
