# Generated by Django 4.1.6 on 2023-05-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0005_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'IQdUFGl-MZ6SRiD7jw8eTmZRQQaq-2bPEx-zzpYnXlE='),
        ),
    ]
