# Generated by Django 4.1.6 on 2023-05-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0005_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'XG_EXjeOPme-F86xPV-sfIZh9NPJYxl-1pQv1h-pt9Q='),
        ),
    ]
