# Generated by Django 4.1.6 on 2023-05-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0008_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'E5cp7H73-F9U1M5z6fOu5V7KpPozb_l1Oosu0fnBrs4='),
        ),
    ]
