# Generated by Django 4.1.6 on 2023-05-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0010_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'GHXmeui1HPocev_4uWSXMdKH8jzBfJQVTZj1o_MG8Eg='),
        ),
    ]
