# Generated by Django 4.1.6 on 2023-05-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0011_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'JsPAETFD6gXMk6RJs3SS111Kcfv-IDmZTLEJHA9HPBk='),
        ),
    ]
