# Generated by Django 4.1.6 on 2023-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0012_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'YV-3v7t0xaehS7qkV6W9C_87q0NAtjViUc22RyyxwTk='),
        ),
    ]
