# Generated by Django 4.1.6 on 2023-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinlink', '0015_alter_public_link_fernet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_link',
            name='fernet_key',
            field=models.BinaryField(default=b'Vxtp54-BmmEkwuz0zp-OQUvPIm0iP13hV9_54MYnbHw='),
        ),
    ]
